repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v5.0.8
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
