---
- name: Accept SSH fingerprint
  hosts: all
  gather_facts: false
  tasks:
  - name: Accept SSH host key
    connection: local
    become: false
    shell: |
      ssh-keygen -F {{ hostvars[inventory_hostname]["ipv4"] }} ||
      ssh-keyscan {{ hostvars[inventory_hostname]["ipv4"] }} >> ~/.ssh/known_hosts
    register: known_hosts_script
    changed_when: "'found' not in known_hosts_script.stdout"
  tags:
    - general

- name: Base setup
  hosts: all
  user: root
  roles:
    - debian_base
  vars:
    - install_docker: true
  tags:
    - general

- name: Jellyfin setup
  hosts: all
  remote_user: deploy
  become: true
  become_user: root
  roles:
    - jellyfin
  vars:
    - restart_traefik: true
  tags:
    - jellyfin
