---
- name: Set up docker
  ansible.builtin.import_role:
    name: crivetimihai.virtualization.docker

- name: Add user to docker group
  ansible.builtin.user:
    name: deploy
    append: true
    groups: docker

- name: Install docker-compose
  ansible.builtin.apt:
    name: docker-compose
