---
- include_tasks: packages.yml
- include_tasks: user.yml
- include_tasks: firewall.yml
- include_tasks: hardening.yml
- include_tasks: unattended-upgrades.yml
- include_tasks: docker.yml
  when: install_docker|bool
